/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banque_du_sang_Views;

import banque_du_sang_DataBase.UtilJDBC;
import banque_du_sang_Models.DetailsDonation;
import java.util.ArrayList;
import java.awt.Font;
import java.sql.SQLException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mmtsh
 */
public class DetailsDonationView extends javax.swing.JPanel {

    
    int mousePX;
    int mousePY;
    int row;
    int ID;
    String order;
    Connection conn;
    ArrayList<DetailsDonation> details = new ArrayList<>();
    DefaultTableModel df = new DefaultTableModel();
    
    
    
    public DetailsDonationView() {
        initComponents();
        df = (DefaultTableModel) tableDetailsDonation.getModel();
        conn = UtilJDBC.seConnecte();
        Afficher();
        
        
        /* Make Modify,Delete and imprime invisible until select some row */
        btnSupprimerDonataire.setVisible(false);
        
        panelSearch.setVisible(false);
        AfficherTous.setVisible(false);
        
        
        
        /* Design Table Header */
        tableDetailsDonation.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tableDetailsDonation.getTableHeader().setOpaque(false);
        tableDetailsDonation.setRowHeight(25);
        ((DefaultTableCellRenderer)tableDetailsDonation.getTableHeader().getDefaultRenderer()).setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }
    
    
    
    
    /* Methode to Show Data in table and also add them to List */
    public void Afficher(){
        try {
            Statement st = conn.createStatement();
            String req = "select * from DetailsDonation ";
            if(order == "Nouveau"){
                req+= " order by DonationNum desc";
            }else if(order == "Ancien"){
                req+= " order by DonationNum asc";
            }
            ResultSet rs  = st.executeQuery(req);
            df.setRowCount(0);
            while(rs.next()){
                details.add(new DetailsDonation(rs.getInt(1),rs.getInt(2),rs.getInt(3), rs.getString(4), rs.getDate(5), rs.getInt(6)));
                df.addRow(new Object[]{rs.getInt(1),rs.getInt(2),rs.getInt(3), rs.getString(4), rs.getDate(5), rs.getInt(6)});
            }
            
            rs.close();
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetailsDonation = new javax.swing.JTable();
        btnSupprimerDonataire = new rojeru_san.RSButton();
        panelSearch = new javax.swing.JPanel();
        btnSearchInput = new javax.swing.JLabel();
        txtSearchNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearchInput1 = new javax.swing.JLabel();
        AfficherTous = new javax.swing.JLabel();
        ShowSearch = new javax.swing.JLabel();
        jcmbSortPar = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(884, 592));
        setPreferredSize(new java.awt.Dimension(884, 592));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDetailsDonation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donation Num", "PocheNum", "Donataire ID", "Hospital", "DatePrendre", "QunatitePrendre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDetailsDonation.setFocusable(false);
        tableDetailsDonation.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableDetailsDonation.setRowHeight(25);
        tableDetailsDonation.setSelectionBackground(new java.awt.Color(208, 45, 51));
        tableDetailsDonation.getTableHeader().setReorderingAllowed(false);
        tableDetailsDonation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetailsDonationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDetailsDonation);
        if (tableDetailsDonation.getColumnModel().getColumnCount() > 0) {
            tableDetailsDonation.getColumnModel().getColumn(0).setResizable(false);
            tableDetailsDonation.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableDetailsDonation.getColumnModel().getColumn(2).setPreferredWidth(15);
            tableDetailsDonation.getColumnModel().getColumn(4).setResizable(false);
            tableDetailsDonation.getColumnModel().getColumn(4).setPreferredWidth(16);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 865, 450));

        btnSupprimerDonataire.setBackground(new java.awt.Color(255, 51, 51));
        btnSupprimerDonataire.setText("Supprimer");
        btnSupprimerDonataire.setColorHover(new java.awt.Color(181, 46, 52));
        btnSupprimerDonataire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerDonataireActionPerformed(evt);
            }
        });
        add(btnSupprimerDonataire, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        panelSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchInput.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/searchIconInput.png"))); // NOI18N
        btnSearchInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchInputMouseClicked(evt);
            }
        });
        panelSearch.add(btnSearchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 21, -1, -1));

        txtSearchNom.setForeground(new java.awt.Color(0, 0, 0));
        panelSearch.add(txtSearchNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 210, 38));

        jLabel1.setText("Recherche par nom:");
        panelSearch.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 120, 40));

        btnSearchInput1.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchInput1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/searchIconInput.png"))); // NOI18N
        btnSearchInput1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchInput1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchInput1MouseClicked(evt);
            }
        });
        panelSearch.add(btnSearchInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 21, 30, -1));

        AfficherTous.setForeground(new java.awt.Color(255, 51, 51));
        AfficherTous.setText("Afficher Tous");
        AfficherTous.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AfficherTous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AfficherTousMouseClicked(evt);
            }
        });
        panelSearch.add(AfficherTous, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 90, 30));

        add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 0, 340, 80));

        ShowSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/searchIconInput.png"))); // NOI18N
        ShowSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowSearchMouseClicked(evt);
            }
        });
        add(ShowSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 14, 30, 40));

        jcmbSortPar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Nouveau", "Ancien" }));
        jcmbSortPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbSortParActionPerformed(evt);
            }
        });
        add(jcmbSortPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, 100, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sort par:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void tableDetailsDonationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetailsDonationMouseClicked
        btnSupprimerDonataire.setVisible(true);
    }//GEN-LAST:event_tableDetailsDonationMouseClicked

    private void btnSupprimerDonataireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerDonataireActionPerformed
        int agree = JOptionPane.showConfirmDialog(null, "Voulez Vous supprimer cette Details?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(agree==JOptionPane.YES_OPTION){
            DetailsDonation d = details.get(row);
            ID = d.getDonationNum();
            try {
                PreparedStatement ps  = conn.prepareStatement("delete from DetailsDonation where DonationNum=?");
                ps.setInt(1, ID);
                ps.executeQuery();
                details.remove(d);
                Afficher();
                JOptionPane.showMessageDialog(null, "Details a ete supprimer avec succes");
            } catch (SQLException ex) {
                Logger.getLogger(DetailsDonationView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSupprimerDonataireActionPerformed

    private void btnSearchInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchInputMouseClicked
        String nom = txtSearchNom.getText();
            df.setRowCount(0);
        try {
            PreparedStatement ps = conn.prepareStatement("select * from Donataire where lower(DonataireNom) like lower(?)");
            ps.setString(1,"%"+nom+"%");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                df.addRow(new Object[]{rs.getInt(1),rs.getInt(2),rs.getInt(3), rs.getString(4), rs.getDate(5), rs.getInt(6)});
            }
            AfficherTous.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DetailsDonationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchInputMouseClicked

    private void btnSearchInput1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchInput1MouseClicked
        ShowSearch.setVisible(false);
        panelSearch.setVisible(true);
    }//GEN-LAST:event_btnSearchInput1MouseClicked

    private void ShowSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowSearchMouseClicked
        ShowSearch.setVisible(false);
        panelSearch.setVisible(true);
    }//GEN-LAST:event_ShowSearchMouseClicked

    private void AfficherTousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AfficherTousMouseClicked
        Afficher();
        AfficherTous.setVisible(false);
    }//GEN-LAST:event_AfficherTousMouseClicked

    private void jcmbSortParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbSortParActionPerformed
        order = (String) jcmbSortPar.getSelectedItem();
        Afficher();
    }//GEN-LAST:event_jcmbSortParActionPerformed


   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfficherTous;
    private javax.swing.JLabel ShowSearch;
    private javax.swing.JLabel btnSearchInput;
    private javax.swing.JLabel btnSearchInput1;
    private rojeru_san.RSButton btnSupprimerDonataire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcmbSortPar;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JTable tableDetailsDonation;
    private javax.swing.JTextField txtSearchNom;
    // End of variables declaration//GEN-END:variables
}
