/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banque_du_sang_Views;

import banque_du_sang_DataBase.UtilJDBC;
import banque_du_sang_Models.Donneur;
import java.awt.Desktop;
import java.util.ArrayList;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import rojeru_san.NewJFrame;

/**
 *
 * @author mmtsh
 */
public class DonneurView extends javax.swing.JPanel {

    
    int mousePX;
    int mousePY;
    int row;
    int ID;
    String order;
    String action;
    Connection conn;
    ArrayList<Donneur> donneur = new ArrayList<Donneur>();
    DefaultTableModel df = new DefaultTableModel();
    
    
    
    public DonneurView() {
        initComponents();
        df = (DefaultTableModel) tableDonneur.getModel();
        conn = UtilJDBC.seConnecte();
        Afficher();
        
       
        
        /* Make Modify,Delete and imprime invisible until select some row */
        btnSupprimerDonneur.setVisible(false);
        btnImprimerInfos.setVisible(false);
        btnModifierDonneur.setVisible(false);
        btnFirst.setVisible(false);
        btnPrevious.setVisible(false);
        btnNext.setVisible(false);
        btnLast.setVisible(false);
        
        panelSearch.setVisible(false);
        btnSearchGender.setSelected(true);
        AfficherTous.setVisible(false);
        
        labelDateFormat.setVisible(false);
        
        
        /* Design Table Header */
        tableDonneur.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tableDonneur.getTableHeader().setOpaque(false);
        tableDonneur.setRowHeight(25);
        ((DefaultTableCellRenderer)tableDonneur.getTableHeader().getDefaultRenderer()).setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }
    
    
    
    
    /* Methode to Show Data in table and also add them to List */
    public void Afficher(){
        try {
            Statement st = conn.createStatement();
            String req = "select * from Donneur ";
            if(order == "Nouveau"){
                req+= " order by DonneurID desc";
            }else if(order == "Ancien"){
                req+= " order by DonneurID asc";
            }
            ResultSet rs  = st.executeQuery(req);
            df.setRowCount(0);
            while(rs.next()){
                donneur.add(new Donneur(rs.getInt(1),rs.getString(2),rs.getString(3), rs.getDate(4), rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8),rs.getString(9)));
                df.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3), rs.getDate(4), rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8),rs.getString(9)});
            }
            
            rs.close();
            st.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    
    /* Remplir les input pour la modification */
    public void remplirInputs(){
        Donneur d = donneur.get(row);
        txtNomDonneur.setText(d.getDonneurNom());
        txtDateNaiss.setText(d.getDonneurDateNaiss()+"");
        txtAdresseDonneur.setText(d.getDonneurAdresse());
        txtTeleDonneur.setText(d.getDonneurTele()+"");
        txtVilleDonneur.setText(d.getDonneurVille());
        jcmbEligibility.setSelectedItem(d.getEligibility());
        String gender = d.getDonneurSexe();
        if(gender.equals("Male")){
            jrbtnMale.setSelected(true);
        }else{
            jrbtnFemale.setSelected(true);
        }
        jcmbTypeSang.setSelectedItem(d.getDonneurTypeSang());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nouveauDonneurFrame = new javax.swing.JFrame();
        containerPanel = new javax.swing.JPanel();
        ClosePanel2 = new javax.swing.JPanel();
        btnMinimize2 = new javax.swing.JLabel();
        btnClose2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jLabel3 = new javax.swing.JLabel();
        txtNomDonneur = new rojeru_san.RSMTextFull();
        txtDateNaiss = new rojeru_san.RSMTextFull();
        jLabel5 = new javax.swing.JLabel();
        jrbtnMale = new javax.swing.JRadioButton();
        jrbtnFemale = new javax.swing.JRadioButton();
        jcmbTypeSang = new javax.swing.JComboBox();
        txtVilleDonneur = new rojeru_san.RSMTextFull();
        txtTeleDonneur = new rojeru_san.RSMTextFull();
        btnBack = new rojeru_san.RSButtonRiple();
        btnSubmit = new rojeru_san.RSButtonRiple();
        btnFirst = new rojeru_san.RSButton();
        btnPrevious = new rojeru_san.RSButton();
        btnNext = new rojeru_san.RSButton();
        btnLast = new rojeru_san.RSButton();
        jLabel6 = new javax.swing.JLabel();
        txtAdresseDonneur = new rojeru_san.RSMTextFull();
        labelDateFormat = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcmbEligibility = new javax.swing.JComboBox();
        btnGroupGender = new javax.swing.ButtonGroup();
        searchFrame = new javax.swing.JFrame();
        containerPanel1 = new javax.swing.JPanel();
        ClosePanel3 = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        bodyPanel1 = new javax.swing.JPanel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jLabel7 = new javax.swing.JLabel();
        jrbtnSearchMale = new javax.swing.JRadioButton();
        jrbtnSearchFemale = new javax.swing.JRadioButton();
        txtSearchVille = new rojeru_san.RSMTextFull();
        btnRecherche = new rojeru_san.RSButtonRiple();
        jLabel8 = new javax.swing.JLabel();
        jcmbSearchTypeSang = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnSearchTypeSang = new javax.swing.JRadioButton();
        btnSearchGender = new javax.swing.JRadioButton();
        btnSearchVille = new javax.swing.JRadioButton();
        btnGroupSearch = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDonneur = new javax.swing.JTable();
        btnNouveauDonneur = new rojeru_san.RSButton();
        btnImprimerInfos = new rojeru_san.RSButton();
        btnSupprimerDonneur = new rojeru_san.RSButton();
        btnModifierDonneur = new rojeru_san.RSButton();
        panelSearch = new javax.swing.JPanel();
        btnSearchInput = new javax.swing.JLabel();
        txtSearchNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        advencedSearch = new javax.swing.JLabel();
        btnSearchInput1 = new javax.swing.JLabel();
        AfficherTous = new javax.swing.JLabel();
        ShowSearch = new javax.swing.JLabel();
        jcmbSortPar = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        nouveauDonneurFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        nouveauDonneurFrame.setTitle("Ajouter Donneur");
        nouveauDonneurFrame.setLocation(new java.awt.Point(500, 130));
        nouveauDonneurFrame.setMinimumSize(new java.awt.Dimension(469, 674));
        nouveauDonneurFrame.setUndecorated(true);
        nouveauDonneurFrame.setSize(new java.awt.Dimension(469, 674));

        containerPanel.setMinimumSize(new java.awt.Dimension(469, 646));
        containerPanel.setPreferredSize(new java.awt.Dimension(795, 646));
        containerPanel.setLayout(null);

        ClosePanel2.setBackground(new java.awt.Color(0, 0, 0));
        ClosePanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClosePanel2.setPreferredSize(new java.awt.Dimension(33, 33));
        ClosePanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ClosePanel2MouseDragged(evt);
            }
        });
        ClosePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClosePanel2MousePressed(evt);
            }
        });
        ClosePanel2.setLayout(null);

        btnMinimize2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Minimze.png"))); // NOI18N
        btnMinimize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimize2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimize2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimize2MouseExited(evt);
            }
        });
        ClosePanel2.add(btnMinimize2);
        btnMinimize2.setBounds(390, 0, 30, 33);

        btnClose2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Closee.png"))); // NOI18N
        btnClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClose2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClose2MouseExited(evt);
            }
        });
        ClosePanel2.add(btnClose2);
        btnClose2.setBounds(430, 0, 30, 33);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        ClosePanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 35);

        containerPanel.add(ClosePanel2);
        ClosePanel2.setBounds(0, 0, 480, 35);

        bodyPanel.setBackground(new java.awt.Color(181, 46, 52));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelShadow1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nouveau Donneur");
        rSPanelShadow1.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        bodyPanel.add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 330, 48));

        txtNomDonneur.setBackground(new java.awt.Color(181, 46, 52));
        txtNomDonneur.setForeground(new java.awt.Color(255, 255, 255));
        txtNomDonneur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomDonneur.setBordeColorFocus(new java.awt.Color(255, 0, 0));
        txtNomDonneur.setBotonColor(new java.awt.Color(102, 0, 0));
        txtNomDonneur.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        txtNomDonneur.setMargin(new java.awt.Insets(2, 6, 2, 6));
        txtNomDonneur.setPlaceholder("Nom Complet de Donneur");
        txtNomDonneur.setSoloLetras(true);
        bodyPanel.add(txtNomDonneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 270, 40));

        txtDateNaiss.setBackground(new java.awt.Color(181, 46, 52));
        txtDateNaiss.setForeground(new java.awt.Color(255, 255, 255));
        txtDateNaiss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDateNaiss.setBordeColorFocus(new java.awt.Color(255, 0, 0));
        txtDateNaiss.setBotonColor(new java.awt.Color(102, 0, 0));
        txtDateNaiss.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        txtDateNaiss.setMargin(new java.awt.Insets(2, 6, 2, 6));
        txtDateNaiss.setPlaceholder("YYYY-MM-DD");
        txtDateNaiss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateNaissKeyPressed(evt);
            }
        });
        bodyPanel.add(txtDateNaiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 130, 40));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date Naissance");
        bodyPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 30));

        jrbtnMale.setBackground(new java.awt.Color(181, 46, 52));
        btnGroupGender.add(jrbtnMale);
        jrbtnMale.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnMale.setText("Male");
        bodyPanel.add(jrbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jrbtnFemale.setBackground(new java.awt.Color(181, 46, 52));
        btnGroupGender.add(jrbtnFemale);
        jrbtnFemale.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnFemale.setText("Female");
        bodyPanel.add(jrbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jcmbTypeSang.setBackground(new java.awt.Color(181, 46, 52));
        jcmbTypeSang.setForeground(new java.awt.Color(255, 255, 255));
        jcmbTypeSang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bodyPanel.add(jcmbTypeSang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 130, -1));

        txtVilleDonneur.setBackground(new java.awt.Color(181, 46, 52));
        txtVilleDonneur.setForeground(new java.awt.Color(255, 255, 255));
        txtVilleDonneur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVilleDonneur.setBordeColorFocus(new java.awt.Color(255, 0, 0));
        txtVilleDonneur.setBotonColor(new java.awt.Color(102, 0, 0));
        txtVilleDonneur.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        txtVilleDonneur.setMargin(new java.awt.Insets(2, 6, 2, 6));
        txtVilleDonneur.setPlaceholder("Ville");
        bodyPanel.add(txtVilleDonneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 270, 40));

        txtTeleDonneur.setBackground(new java.awt.Color(181, 46, 52));
        txtTeleDonneur.setForeground(new java.awt.Color(255, 255, 255));
        txtTeleDonneur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTeleDonneur.setBordeColorFocus(new java.awt.Color(255, 0, 0));
        txtTeleDonneur.setBotonColor(new java.awt.Color(102, 0, 0));
        txtTeleDonneur.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        txtTeleDonneur.setMargin(new java.awt.Insets(2, 6, 2, 6));
        txtTeleDonneur.setPlaceholder("+212");
        txtTeleDonneur.setSoloNumeros(true);
        bodyPanel.add(txtTeleDonneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 270, 40));

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setText("Back");
        btnBack.setColorHover(new java.awt.Color(204, 0, 102));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        bodyPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 190, -1));

        btnSubmit.setBackground(new java.awt.Color(51, 51, 51));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        bodyPanel.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 190, -1));

        btnFirst.setBackground(new java.awt.Color(51, 51, 51));
        btnFirst.setText("|<");
        btnFirst.setColorHover(new java.awt.Color(204, 51, 0));
        btnFirst.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        bodyPanel.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 70, -1));

        btnPrevious.setBackground(new java.awt.Color(51, 51, 51));
        btnPrevious.setText("<");
        btnPrevious.setColorHover(new java.awt.Color(204, 51, 0));
        btnPrevious.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        bodyPanel.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 70, -1));

        btnNext.setBackground(new java.awt.Color(51, 51, 51));
        btnNext.setText(">");
        btnNext.setColorHover(new java.awt.Color(204, 51, 0));
        btnNext.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        bodyPanel.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 70, -1));

        btnLast.setBackground(new java.awt.Color(51, 51, 51));
        btnLast.setText(">|");
        btnLast.setColorHover(new java.awt.Color(204, 51, 0));
        btnLast.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        bodyPanel.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 70, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type de Sang");
        bodyPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, 40));

        txtAdresseDonneur.setBackground(new java.awt.Color(181, 46, 52));
        txtAdresseDonneur.setForeground(new java.awt.Color(255, 255, 255));
        txtAdresseDonneur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAdresseDonneur.setBordeColorFocus(new java.awt.Color(255, 0, 0));
        txtAdresseDonneur.setBotonColor(new java.awt.Color(102, 0, 0));
        txtAdresseDonneur.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        txtAdresseDonneur.setMargin(new java.awt.Insets(2, 6, 2, 6));
        txtAdresseDonneur.setPlaceholder("Adresse");
        bodyPanel.add(txtAdresseDonneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 270, 40));

        labelDateFormat.setForeground(new java.awt.Color(153, 153, 153));
        labelDateFormat.setText("YYYY-MM-DD");
        bodyPanel.add(labelDateFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 80, 30));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eligibility");
        bodyPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 90, 40));

        jcmbEligibility.setBackground(new java.awt.Color(181, 46, 52));
        jcmbEligibility.setForeground(new java.awt.Color(255, 255, 255));
        jcmbEligibility.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rejete", "Acceptable" }));
        bodyPanel.add(jcmbEligibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 130, -1));

        containerPanel.add(bodyPanel);
        bodyPanel.setBounds(0, 33, 472, 640);

        javax.swing.GroupLayout nouveauDonneurFrameLayout = new javax.swing.GroupLayout(nouveauDonneurFrame.getContentPane());
        nouveauDonneurFrame.getContentPane().setLayout(nouveauDonneurFrameLayout);
        nouveauDonneurFrameLayout.setHorizontalGroup(
            nouveauDonneurFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        nouveauDonneurFrameLayout.setVerticalGroup(
            nouveauDonneurFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        searchFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        searchFrame.setTitle("Ajouter Donneur");
        searchFrame.setLocation(new java.awt.Point(500, 130));
        searchFrame.setMinimumSize(new java.awt.Dimension(469, 450));
        searchFrame.setUndecorated(true);
        searchFrame.setSize(new java.awt.Dimension(469, 450));

        containerPanel1.setMinimumSize(new java.awt.Dimension(469, 646));
        containerPanel1.setPreferredSize(new java.awt.Dimension(795, 646));
        containerPanel1.setLayout(null);

        ClosePanel3.setBackground(new java.awt.Color(0, 0, 0));
        ClosePanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClosePanel3.setPreferredSize(new java.awt.Dimension(33, 33));
        ClosePanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ClosePanel3MouseDragged(evt);
            }
        });
        ClosePanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClosePanel3MousePressed(evt);
            }
        });
        ClosePanel3.setLayout(null);

        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Minimze.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseExited(evt);
            }
        });
        ClosePanel3.add(btnMinimize);
        btnMinimize.setBounds(390, 0, 30, 33);

        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Closee.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        ClosePanel3.add(btnClose);
        btnClose.setBounds(430, 0, 30, 33);

        jLabel.setBackground(new java.awt.Color(0, 0, 0));
        jLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelMouseDragged(evt);
            }
        });
        jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMousePressed(evt);
            }
        });
        ClosePanel3.add(jLabel);
        jLabel.setBounds(0, 0, 480, 35);

        containerPanel1.add(ClosePanel3);
        ClosePanel3.setBounds(0, 0, 480, 35);

        bodyPanel1.setBackground(new java.awt.Color(181, 46, 52));
        bodyPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelShadow2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Recherche");
        rSPanelShadow2.add(jLabel7, java.awt.BorderLayout.PAGE_END);

        bodyPanel1.add(rSPanelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 330, 48));

        jrbtnSearchMale.setBackground(new java.awt.Color(181, 46, 52));
        btnGroupGender.add(jrbtnSearchMale);
        jrbtnSearchMale.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnSearchMale.setText("Male");
        bodyPanel1.add(jrbtnSearchMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jrbtnSearchFemale.setBackground(new java.awt.Color(181, 46, 52));
        btnGroupGender.add(jrbtnSearchFemale);
        jrbtnSearchFemale.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnSearchFemale.setText("Female");
        bodyPanel1.add(jrbtnSearchFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        txtSearchVille.setBackground(new java.awt.Color(181, 46, 52));
        txtSearchVille.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchVille.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchVille.setBordeColorFocus(new java.awt.Color(255, 0, 0));
        txtSearchVille.setBotonColor(new java.awt.Color(102, 0, 0));
        txtSearchVille.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        txtSearchVille.setMargin(new java.awt.Insets(2, 6, 2, 6));
        txtSearchVille.setPlaceholder("Ville");
        bodyPanel1.add(txtSearchVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 220, 40));

        btnRecherche.setBackground(new java.awt.Color(51, 51, 51));
        btnRecherche.setText("Recherche");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });
        bodyPanel1.add(btnRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 190, -1));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Type de Sang");
        bodyPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 90, 40));

        jcmbSearchTypeSang.setBackground(new java.awt.Color(181, 46, 52));
        jcmbSearchTypeSang.setForeground(new java.awt.Color(255, 255, 255));
        jcmbSearchTypeSang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bodyPanel1.add(jcmbSearchTypeSang, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 100, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        bodyPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 430, 20));

        jSeparator2.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        bodyPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 430, 20));

        jSeparator3.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        bodyPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 430, 20));

        jSeparator4.setBackground(new java.awt.Color(255, 51, 0));
        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        bodyPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 430, 20));

        btnGroupSearch.add(btnSearchTypeSang);
        btnSearchTypeSang.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchTypeSang.setText("Recherche par:");
        bodyPanel1.add(btnSearchTypeSang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 40));

        btnGroupSearch.add(btnSearchGender);
        btnSearchGender.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchGender.setText("Recherche par Sexe:");
        bodyPanel1.add(btnSearchGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, -1));

        btnGroupSearch.add(btnSearchVille);
        btnSearchVille.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchVille.setText("Recherche par Ville:");
        bodyPanel1.add(btnSearchVille, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 50));

        containerPanel1.add(bodyPanel1);
        bodyPanel1.setBounds(0, 33, 472, 420);

        javax.swing.GroupLayout searchFrameLayout = new javax.swing.GroupLayout(searchFrame.getContentPane());
        searchFrame.getContentPane().setLayout(searchFrameLayout);
        searchFrameLayout.setHorizontalGroup(
            searchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        searchFrameLayout.setVerticalGroup(
            searchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setMinimumSize(new java.awt.Dimension(884, 592));
        setPreferredSize(new java.awt.Dimension(884, 592));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDonneur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Sexe", "Date Naissance", "Type Sang", "Adresse", "Ville", "Tele", "Eligibility"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDonneur.setFocusable(false);
        tableDonneur.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableDonneur.setRowHeight(25);
        tableDonneur.setSelectionBackground(new java.awt.Color(208, 45, 51));
        tableDonneur.getTableHeader().setReorderingAllowed(false);
        tableDonneur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDonneurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDonneur);
        if (tableDonneur.getColumnModel().getColumnCount() > 0) {
            tableDonneur.getColumnModel().getColumn(0).setResizable(false);
            tableDonneur.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableDonneur.getColumnModel().getColumn(2).setPreferredWidth(15);
            tableDonneur.getColumnModel().getColumn(4).setResizable(false);
            tableDonneur.getColumnModel().getColumn(4).setPreferredWidth(16);
            tableDonneur.getColumnModel().getColumn(6).setPreferredWidth(38);
            tableDonneur.getColumnModel().getColumn(7).setPreferredWidth(35);
            tableDonneur.getColumnModel().getColumn(8).setPreferredWidth(25);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 865, 450));

        btnNouveauDonneur.setBackground(new java.awt.Color(255, 51, 51));
        btnNouveauDonneur.setText("Nouveau Donneur");
        btnNouveauDonneur.setColorHover(new java.awt.Color(181, 46, 52));
        btnNouveauDonneur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauDonneurActionPerformed(evt);
            }
        });
        add(btnNouveauDonneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 16, -1, -1));

        btnImprimerInfos.setBackground(new java.awt.Color(255, 51, 51));
        btnImprimerInfos.setText("Imprimer");
        btnImprimerInfos.setColorHover(new java.awt.Color(181, 46, 52));
        btnImprimerInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerInfosActionPerformed(evt);
            }
        });
        add(btnImprimerInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 543, -1, -1));

        btnSupprimerDonneur.setBackground(new java.awt.Color(255, 51, 51));
        btnSupprimerDonneur.setText("Supprimer");
        btnSupprimerDonneur.setColorHover(new java.awt.Color(181, 46, 52));
        btnSupprimerDonneur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerDonneurActionPerformed(evt);
            }
        });
        add(btnSupprimerDonneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 543, -1, -1));

        btnModifierDonneur.setBackground(new java.awt.Color(255, 51, 51));
        btnModifierDonneur.setText("Modifier Donneur");
        btnModifierDonneur.setColorHover(new java.awt.Color(181, 46, 52));
        btnModifierDonneur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierDonneurActionPerformed(evt);
            }
        });
        add(btnModifierDonneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 543, -1, -1));

        panelSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchInput.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/searchIconInput.png"))); // NOI18N
        btnSearchInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchInputMouseClicked(evt);
            }
        });
        panelSearch.add(btnSearchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 21, -1, -1));

        txtSearchNom.setForeground(new java.awt.Color(0, 0, 0));
        panelSearch.add(txtSearchNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 210, 38));

        jLabel1.setText("Recherche par nom:");
        panelSearch.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 120, 40));

        advencedSearch.setForeground(new java.awt.Color(255, 51, 51));
        advencedSearch.setText("Advenced Search");
        advencedSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advencedSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advencedSearchMouseClicked(evt);
            }
        });
        panelSearch.add(advencedSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 56, 100, 20));

        btnSearchInput1.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchInput1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/searchIconInput.png"))); // NOI18N
        btnSearchInput1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchInput1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchInput1MouseClicked(evt);
            }
        });
        panelSearch.add(btnSearchInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 21, 30, -1));

        AfficherTous.setForeground(new java.awt.Color(255, 51, 51));
        AfficherTous.setText("Afficher Tous");
        AfficherTous.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AfficherTous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AfficherTousMouseClicked(evt);
            }
        });
        panelSearch.add(AfficherTous, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 90, 30));

        add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 0, 340, 80));

        ShowSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/searchIconInput.png"))); // NOI18N
        ShowSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowSearchMouseClicked(evt);
            }
        });
        add(ShowSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 14, 30, 40));

        jcmbSortPar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Nouveau", "Ancien" }));
        jcmbSortPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbSortParActionPerformed(evt);
            }
        });
        add(jcmbSortPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, 100, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sort par:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void tableDonneurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDonneurMouseClicked
        btnSupprimerDonneur.setVisible(true);
        btnImprimerInfos.setVisible(true);
        btnModifierDonneur.setVisible(true);
    }//GEN-LAST:event_tableDonneurMouseClicked

    private void btnNouveauDonneurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauDonneurActionPerformed
        action = "ajouter";
        btnFirst.setVisible(false);
        btnPrevious.setVisible(false);
        btnNext.setVisible(false);
        btnLast.setVisible(false);
        txtNomDonneur.setText("");
        txtDateNaiss.setText("");
        txtAdresseDonneur.setText("");
        txtTeleDonneur.setText("");
        txtVilleDonneur.setText("");
        jrbtnMale.setSelected(true);
        jcmbTypeSang.setSelectedIndex(0);
        jLabel3.setText("Nouveau Donneur");
        nouveauDonneurFrame.setVisible(true);
    }//GEN-LAST:event_btnNouveauDonneurActionPerformed

    private void btnMinimize2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize2MouseClicked
        nouveauDonneurFrame.setState(nouveauDonneurFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimize2MouseClicked

    private void btnMinimize2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize2MouseEntered
        btnMinimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/MinimzeHover.png")));
    }//GEN-LAST:event_btnMinimize2MouseEntered

    private void btnMinimize2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize2MouseExited
        btnMinimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Minimze.png")));
    }//GEN-LAST:event_btnMinimize2MouseExited

    private void btnClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose2MouseClicked
        nouveauDonneurFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_btnClose2MouseClicked

    private void btnClose2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose2MouseEntered
        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CloseHover.png")));
    }//GEN-LAST:event_btnClose2MouseEntered

    private void btnClose2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose2MouseExited
        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Closee.png")));
    }//GEN-LAST:event_btnClose2MouseExited

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        nouveauDonneurFrame.setLocation(x - mousePX, y-mousePY);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void ClosePanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ClosePanel2MouseDragged

    private void ClosePanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClosePanel2MousePressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        nouveauDonneurFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String nom = txtNomDonneur.getText();
        String gender = "";
        if(jrbtnMale.isSelected()){
            gender="Male";
        }else{
            gender="Female";
        }
        String typeSang = jcmbTypeSang.getSelectedItem().toString();
        String adresse = txtDateNaiss.getText();
        String ville = txtVilleDonneur.getText();
        java.sql.Date date = java.sql.Date.valueOf(txtDateNaiss.getText());
        int tele = Integer.parseInt(txtTeleDonneur.getText());
        String eligibility = (String) jcmbEligibility.getSelectedItem();
            PreparedStatement ps = null;
        try {
            if(action.equals("ajouter")){
                ps = conn.prepareStatement("insert into Donneur values(seq_DonneurID.nextval,?,?,?,?,?,?,?,?)");
                ps.setString(1, nom);
                ps.setString(2, gender);
                ps.setDate(3, date);
                ps.setString(4, typeSang);
                ps.setString(5, adresse);
                ps.setString(6, ville);
                ps.setInt(7, tele);
                ps.setString(8, eligibility);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Donneur a ete ajoute avec succes");
                txtNomDonneur.setText("");
                txtDateNaiss.setText("");
                txtAdresseDonneur.setText("");
                txtTeleDonneur.setText("");
                txtVilleDonneur.setText("");
            }else if(action.equals("modifier")){
                ps = conn.prepareStatement("update Donneur set DonneurNom=?, DonneurSexe=?, DonneurDateNaiss=?, DonneurTypeSang=?, DonneurAdresse=?, DonneurVille=?, DonneurTele=?, Eligibility=? where DonneurID=?");
                Donneur d = donneur.get(row);
                ID = d.getDonneurId();
                ps.setString(1, nom);
                ps.setString(2, gender);
                ps.setDate(3, date);
                ps.setString(4, typeSang);
                ps.setString(5, adresse);
                ps.setString(6, ville);
                ps.setInt(7, tele);
                ps.setString(8, eligibility);
                ps.setInt(9, ID);
                ps.executeUpdate();
                d.setDonneurNom(nom);
                d.setDonneurSexe(gender);
                d.setDonneurDateNaiss(date);
                d.setDonneurTypeSang(typeSang);
                d.setDonneurAdresse(adresse);
                d.setDonneurVille(ville);
                d.setDonneurTele(tele);
                d.setEligibility(eligibility);
                JOptionPane.showMessageDialog(null, "Donneur a ete modifie avec succes");
            }
            
            Afficher();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnModifierDonneurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierDonneurActionPerformed
        if(tableDonneur.getSelectedRow() != -1){
            row = tableDonneur.getSelectedRow();
            ID = (int) tableDonneur.getValueAt(row, 0);
        }
        remplirInputs();
        action = "modifier";
        btnFirst.setVisible(true);
        btnPrevious.setVisible(true);
        btnNext.setVisible(true);
        btnLast.setVisible(true);
        jLabel3.setText("Modifier Donneur");
        nouveauDonneurFrame.setVisible(true);
    }//GEN-LAST:event_btnModifierDonneurActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        row=0;
        remplirInputs();
        
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(row<donneur.size()-1){
            row++;
            remplirInputs();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        row = donneur.size()-1;
        remplirInputs();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if(row>0){
            row--;
            remplirInputs();
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnSupprimerDonneurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerDonneurActionPerformed
        int agree = JOptionPane.showConfirmDialog(null, "Voulez Vous supprimer ce Donneur?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(agree==JOptionPane.YES_OPTION){
            Donneur d = donneur.get(row);
            ID = d.getDonneurId();
            try {
                PreparedStatement ps  = conn.prepareStatement("delete from Donneur where DonneurID=?");
                ps.setInt(1, ID);
                ps.executeQuery();
                donneur.remove(d);
                Afficher();
                JOptionPane.showMessageDialog(null, "Le Donneur a ete supprimer avec succes");
            } catch (SQLException ex) {
                Logger.getLogger(DonneurView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSupprimerDonneurActionPerformed

    private void txtDateNaissKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateNaissKeyPressed
        labelDateFormat.setVisible(true);
    }//GEN-LAST:event_txtDateNaissKeyPressed

    private void btnSearchInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchInputMouseClicked
        String nom = txtSearchNom.getText();
            df.setRowCount(0);
        try {
            PreparedStatement ps = conn.prepareStatement("select * from Donneur where lower(DonneurNom) like lower(?)");
            ps.setString(1,"%"+nom+"%");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                df.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3), rs.getDate(4), rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8),rs.getString(9)});
            }
            AfficherTous.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DonneurView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchInputMouseClicked

    private void advencedSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advencedSearchMouseClicked
        searchFrame.setVisible(true);
    }//GEN-LAST:event_advencedSearchMouseClicked

    private void btnSearchInput1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchInput1MouseClicked
        ShowSearch.setVisible(false);
        panelSearch.setVisible(true);
    }//GEN-LAST:event_btnSearchInput1MouseClicked

    private void ShowSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowSearchMouseClicked
        ShowSearch.setVisible(false);
        panelSearch.setVisible(true);
    }//GEN-LAST:event_ShowSearchMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        searchFrame.setState(searchFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/MinimzeHover.png")));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseExited
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Minimze.png")));
    }//GEN-LAST:event_btnMinimizeMouseExited

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        searchFrame.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CloseHover.png")));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
       btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Closee.png")));
    }//GEN-LAST:event_btnCloseMouseExited

    private void jLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        searchFrame.setLocation(x - mousePX, y-mousePY);
    }//GEN-LAST:event_jLabelMouseDragged

    private void jLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMousePressed
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_jLabelMousePressed

    private void ClosePanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePanel3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ClosePanel3MouseDragged

    private void ClosePanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePanel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClosePanel3MousePressed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        String requette = "select * from Donneur ";
        df.setRowCount(0);
        PreparedStatement ps= null;
        try {
        if(btnSearchGender.isSelected()){
            String gender = "";
            if(jrbtnSearchMale.isSelected()){
                gender="Male";
            }else if(jrbtnSearchFemale.isSelected()){
                gender="Female";
            }
            requette += " where lower(DonneurSexe) = lower(?)";
            ps = conn.prepareStatement(requette);
            ps.setString(1, gender);
        }else if(btnSearchVille.isSelected()){
            String ville = txtSearchVille.getText();
            requette += " where lower (DonneurVille) like lower(?)";
            ps = conn.prepareStatement(requette);
            ps.setString(1, "%"+ville+"%");
        }else{
            String typeSang = (String) jcmbSearchTypeSang.getSelectedItem();
            requette += " where lower (DonneurTypeSang) = lower (?)";
            ps = conn.prepareStatement(requette);
            ps.setString(1, typeSang);
        }
        ResultSet rs = ps.executeQuery();
        AfficherTous.setVisible(true);
        while(rs.next()){
            df.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3), rs.getDate(4), rs.getString(5),rs.getString(6),rs.getString(7),rs.getInt(8),rs.getString(9)});
        }
        } catch (SQLException ex) {
            Logger.getLogger(DonneurView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void AfficherTousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AfficherTousMouseClicked
        Afficher();
        AfficherTous.setVisible(false);
    }//GEN-LAST:event_AfficherTousMouseClicked

    private void jcmbSortParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbSortParActionPerformed
        order = (String) jcmbSortPar.getSelectedItem();
        Afficher();
    }//GEN-LAST:event_jcmbSortParActionPerformed

    private void btnImprimerInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerInfosActionPerformed
        ID = (int) tableDonneur.getValueAt(row, 0);
        try {
            JasperDesign jsd = JRXmlLoader.load("C:\\Users\\mmtsh\\Documents\\NetBeansProjects\\Banque du sang\\src\\banque_du_snag_Etat\\donneur.jrxml");
            JasperReport jasperReport = JasperCompileManager.compileReport(jsd);
            Map parameters = new HashMap();
            parameters.put("id",ID);
            JasperPrint jsp = JasperFillManager.fillReport(jasperReport , parameters , conn);
            JasperExportManager.exportReportToPdfFile(jsp,"etat_parameter.pdf");
            Desktop d = Desktop.getDesktop();
            d.open(new File("etat_parameter.pdf"));
        } catch (JRException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
           Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnImprimerInfosActionPerformed


   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfficherTous;
    private javax.swing.JPanel ClosePanel2;
    private javax.swing.JPanel ClosePanel3;
    private javax.swing.JLabel ShowSearch;
    private javax.swing.JLabel advencedSearch;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel bodyPanel1;
    private rojeru_san.RSButtonRiple btnBack;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnClose2;
    private rojeru_san.RSButton btnFirst;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.ButtonGroup btnGroupSearch;
    private rojeru_san.RSButton btnImprimerInfos;
    private rojeru_san.RSButton btnLast;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnMinimize2;
    private rojeru_san.RSButton btnModifierDonneur;
    private rojeru_san.RSButton btnNext;
    private rojeru_san.RSButton btnNouveauDonneur;
    private rojeru_san.RSButton btnPrevious;
    private rojeru_san.RSButtonRiple btnRecherche;
    private javax.swing.JRadioButton btnSearchGender;
    private javax.swing.JLabel btnSearchInput;
    private javax.swing.JLabel btnSearchInput1;
    private javax.swing.JRadioButton btnSearchTypeSang;
    private javax.swing.JRadioButton btnSearchVille;
    private rojeru_san.RSButtonRiple btnSubmit;
    private rojeru_san.RSButton btnSupprimerDonneur;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel containerPanel1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox jcmbEligibility;
    private javax.swing.JComboBox jcmbSearchTypeSang;
    private javax.swing.JComboBox jcmbSortPar;
    private javax.swing.JComboBox jcmbTypeSang;
    private javax.swing.JRadioButton jrbtnFemale;
    private javax.swing.JRadioButton jrbtnMale;
    private javax.swing.JRadioButton jrbtnSearchFemale;
    private javax.swing.JRadioButton jrbtnSearchMale;
    private javax.swing.JLabel labelDateFormat;
    private javax.swing.JFrame nouveauDonneurFrame;
    private javax.swing.JPanel panelSearch;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private javax.swing.JFrame searchFrame;
    private javax.swing.JTable tableDonneur;
    private rojeru_san.RSMTextFull txtAdresseDonneur;
    private rojeru_san.RSMTextFull txtDateNaiss;
    private rojeru_san.RSMTextFull txtNomDonneur;
    private javax.swing.JTextField txtSearchNom;
    private rojeru_san.RSMTextFull txtSearchVille;
    private rojeru_san.RSMTextFull txtTeleDonneur;
    private rojeru_san.RSMTextFull txtVilleDonneur;
    // End of variables declaration//GEN-END:variables
}
